export type Lang = "he" | "en";

export const STRINGS = {
  he: {
    brand: "מעקב מועמדויות",
    sub: "נהל את חיפוש העבודה שלך",
    add: "הוסף מועמדות",
    aiTips: "טיפים מ-AI",
    logout: "התנתק",
    all: "הכל",
    active: "בתהליך",
    interview: "ראיון",
    offer: "הצעה",
    rejected: "נדחיתי",
    allFields: "כל התחומים",
    searchPh: "חפש חברה, תפקיד…",
    tableCompany: "חברה",
    tableField: "תחום",
    tableDate: "תאריך הגשה",
    tableProgress: "התקדמות",
    tableCv: 'קו"ח',
    tableNotes: "קישור / הערות",
    view: "צפה",
    emptyTitle: "אין מועמדויות עדיין",
    emptySub: 'לחץ על ״הוסף מועמדות״ כדי להתחיל',
    statTotal: "סה״כ מועמדויות",
    statInterviews: "ראיונות",
    statOffers: "הצעות עבודה",
    statConversion: "אחוז המרה לראיון",
    staleTitle: "{n} מועמדויות לא עודכנו מעל 7 ימים",
    tweaksTitle: "Tweaks",
    theme: "ערכת נושא",
    density: "צפיפות",
    viewType: "תצוגה",
    language: "שפה",
    light: "בהיר",
    dark: "כהה",
    comfortable: "נוח",
    compact: "צפוף",
    tableView: "טבלה",
    cardsView: "כרטיסים",
    kanbanView: "לוח",
    colApplied: "הוגשה",
    colScreen: "סינון",
    colFinal: "ראיון סופי",
    colOffer: "הצעה",
    colRejected: "נדחיתי",
    confirmDelete: "למחוק את המועמדות?",
    loading: "טוען מועמדויות...",
  },
  en: {
    brand: "Job Tracker",
    sub: "Manage your job search",
    add: "Add application",
    aiTips: "AI Tips",
    logout: "Log out",
    all: "All",
    active: "Active",
    interview: "Interviewing",
    offer: "Offer",
    rejected: "Rejected",
    allFields: "All fields",
    searchPh: "Search company, role…",
    tableCompany: "Company",
    tableField: "Field",
    tableDate: "Applied",
    tableProgress: "Progress",
    tableCv: "Resume",
    tableNotes: "Link / notes",
    view: "View",
    emptyTitle: "No applications yet",
    emptySub: 'Click "Add application" to get started',
    statTotal: "Total applications",
    statInterviews: "Interviews",
    statOffers: "Offers",
    statConversion: "Interview rate",
    staleTitle: "{n} applications not updated in 7+ days",
    tweaksTitle: "Tweaks",
    theme: "Theme",
    density: "Density",
    viewType: "View",
    language: "Language",
    light: "Light",
    dark: "Dark",
    comfortable: "Comfortable",
    compact: "Compact",
    tableView: "Table",
    cardsView: "Cards",
    kanbanView: "Kanban",
    colApplied: "Applied",
    colScreen: "Screen",
    colFinal: "Interviewing",
    colOffer: "Offer",
    colRejected: "Rejected",
    confirmDelete: "Delete this application?",
    loading: "Loading applications...",
  },
} as const;

export type Strings = { [K in keyof typeof STRINGS.he]: string };
